// prisma/seed-travel-hub-spain.ts
import { PrismaClient } from "../src/generated/prisma/client";
import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3";

const adapter = new PrismaBetterSqlite3({ url: "file:./dev.db" });
const prisma = new PrismaClient({ adapter });

async function main() {
  const TRIP_TITLE = "Spain Recon Trip - April/May 2026";

  // Remove seed anterior da mesma viagem.
  // Como há cascade delete a partir de Trip, isso limpa os filhos.
  await prisma.trip.deleteMany({
    where: { title: TRIP_TITLE },
  });

  const trip = await prisma.trip.create({
    data: {
      title: TRIP_TITLE,
      country: "Spain",
      startDate: "2026-04-07",
      endDate: "2026-05-07",
      status: "planning",
      baseCurrency: "EUR",
      timezone: "Europe/Madrid",
      dateFormat: "dd/MM/yyyy",
      departureFromHome: "2026-04-06",
      returnHome: "2026-05-08",
      notes:
        [
          "Viagem de reconhecimento para avaliar turismo e potencial de moradia.",
          "Foco prático: bairros, custo de vida, transporte, supermercados, segurança e ritmo real das cidades.",
          "Estratégia principal de deslocamento: trem entre grandes cidades; carro apenas pontualmente se necessário.",
          "Reservas ainda não confirmadas no geral; seed representa planejamento operacional atual.",
        ].join(" "),
    },
  });

  // Métodos de pagamento
  await Promise.all([
    prisma.paymentMethod.create({
      data: {
        tripId: trip.id,
        name: "Revolut EUR",
        type: "debit_card",
        currency: "EUR",
        notes: "Método principal para gastos na Europa.",
      },
    }),
    prisma.paymentMethod.create({
      data: {
        tripId: trip.id,
        name: "Nomad USD",
        type: "debit_card",
        currency: "USD",
        notes: "Backup internacional; pode envolver conversão USD -> EUR.",
      },
    }),
    prisma.paymentMethod.create({
      data: {
        tripId: trip.id,
        name: "Inter Global",
        type: "debit_card",
        currency: "EUR",
        notes: "Conta/cartão de backup.",
      },
    }),
    prisma.paymentMethod.create({
      data: {
        tripId: trip.id,
        name: "Cash EUR",
        type: "cash",
        currency: "EUR",
        notes: "Reserva física para emergências e pequenos gastos.",
      },
    }),
  ]);

  // Documentos
  await prisma.document.createMany({
    data: [
      {
        tripId: trip.id,
        documentType: "passport",
        title: "Passaporte brasileiro",
        issuedAt: "ADD_ISSUE_DATE",
        expiresAt: "ADD_EXPIRY_DATE",
        isCritical: true,
        fileUrl: "",
        description: "Preencher número real e anexar scan/foto.",
        tags: "documento,internacional,entrada",
      },
      {
        tripId: trip.id,
        documentType: "travel_insurance",
        title: "Seguro viagem Schengen",
        issuedAt: "",
        expiresAt: "2026-05-08",
        isCritical: true,
        fileUrl: "",
        description: "Contratar com cobertura mínima adequada para entrada no Espaço Schengen.",
        tags: "seguro,schengen,entrada",
      },
      {
        tripId: trip.id,
        documentType: "drivers_license",
        title: "CNH brasileira",
        issuedAt: "",
        expiresAt: "ADD_CNH_EXPIRY",
        isCritical: false,
        fileUrl: "",
        description: "Levar original.",
        tags: "cnh,carro,dirigir",
      },
      {
        tripId: trip.id,
        documentType: "drivers_license",
        title: "PID / Permissão Internacional para Dirigir",
        issuedAt: "",
        expiresAt: "",
        isCritical: false,
        fileUrl: "",
        description: "Emitir antes da viagem se houver intenção de alugar carro.",
        tags: "pid,dirigir,aluguel",
      },
      {
        tripId: trip.id,
        documentType: "ticket",
        title: "Passagem Brasil -> Madrid -> Brasil",
        issuedAt: "",
        expiresAt: "2026-05-08",
        isCritical: true,
        fileUrl: "",
        description: "Comprar voo internacional de ida e volta.",
        tags: "voo,internacional,madrid",
      },
      {
        tripId: trip.id,
        documentType: "financial_proof",
        title: "Comprovantes financeiros",
        issuedAt: "",
        expiresAt: "",
        isCritical: true,
        fileUrl: "",
        description: "Separar extratos, cartões e evidências de capacidade financeira.",
        tags: "financeiro,entrada,comprovante",
      },
    ],
  });

  // Checklist pré-viagem
  await prisma.checklistItem.createMany({
    data: [
      {
        tripId: trip.id,
        category: "documents",
        title: "Conferir validade do passaporte",
        isCompleted: false,
        dueDate: "2026-03-15",
        description: "Idealmente com folga confortável de validade.",
      },
      {
        tripId: trip.id,
        category: "documents",
        title: "Emitir PID",
        isCompleted: false,
        dueDate: "2026-03-18",
        description: "Necessária se quiser dirigir com mais segurança documental.",
      },
      {
        tripId: trip.id,
        category: "health",
        title: "Contratar seguro viagem",
        isCompleted: false,
        dueDate: "2026-03-20",
        description: "Salvar PDF no app e também offline.",
      },
      {
        tripId: trip.id,
        category: "finance",
        title: "Converter parte do saldo para EUR na Revolut",
        isCompleted: false,
        dueDate: "2026-03-21",
        description: "Deixar saldo em euro antes da viagem.",
      },
      {
        tripId: trip.id,
        category: "finance",
        title: "Separar €300 em dinheiro físico",
        isCompleted: false,
        dueDate: "2026-03-28",
        description: "Emergência, táxi, pequenos gastos.",
      },
      {
        tripId: trip.id,
        category: "transport",
        title: "Comprar voo Brasil -> Madrid -> Brasil",
        isCompleted: false,
        dueDate: "2026-03-16",
        description: "Definir datas exatas de chegada e retorno.",
      },
      {
        tripId: trip.id,
        category: "accommodation",
        title: "Reservar primeiros 4-5 dias em Madrid",
        isCompleted: false,
        dueDate: "2026-03-17",
        description: "Chegada com menos atrito.",
      },
      {
        tripId: trip.id,
        category: "transport",
        title: "Mapear trechos de trem da rota principal",
        isCompleted: false,
        dueDate: "2026-03-22",
        description: "Pode deixar parte para comprar mais perto.",
      },
      {
        tripId: trip.id,
        category: "tech",
        title: "Comprar adaptador de tomada padrão europeu",
        isCompleted: false,
        dueDate: "2026-03-25",
        description: "Tipo C/F.",
      },
      {
        tripId: trip.id,
        category: "tech",
        title: "Organizar notebook, carregadores e power bank",
        isCompleted: false,
        dueDate: "2026-04-03",
        description: "Levar na mochila.",
      },
      {
        tripId: trip.id,
        category: "communication",
        title: "Definir plano de internet móvel / eSIM",
        isCompleted: false,
        dueDate: "2026-04-01",
        description: "Comparar eSIM e chip local.",
      },
      {
        tripId: trip.id,
        category: "packing",
        title: "Montar mala para 7-8 dias e lavar roupa durante a viagem",
        isCompleted: false,
        dueDate: "2026-04-04",
        description: "Evitar excesso de bagagem.",
      },
      {
        tripId: trip.id,
        category: "other",
        title: "Avisar contato da região de Málaga quando a viagem estiver fechada",
        isCompleted: false,
        dueDate: "2026-04-10",
        description: "Marcar encontro apenas quando estiver hospedado em Málaga.",
      },
    ],
  });

  // Packing list
  await prisma.packingItem.createMany({
    data: [
      // Mochila
      {
        tripId: trip.id,
        bagType: "backpack",
        category: "electronics",
        itemName: "Notebook",
        quantity: 1,
        isPacked: false,
      },
      {
        tripId: trip.id,
        bagType: "backpack",
        category: "electronics",
        itemName: "Carregador do notebook",
        quantity: 1,
        isPacked: false,
      },
      {
        tripId: trip.id,
        bagType: "backpack",
        category: "electronics",
        itemName: "Carregador do celular",
        quantity: 1,
        isPacked: false,
      },
      {
        tripId: trip.id,
        bagType: "backpack",
        category: "electronics",
        itemName: "Power bank",
        quantity: 1,
        isPacked: false,
      },
      {
        tripId: trip.id,
        bagType: "backpack",
        category: "documents",
        itemName: "Passaporte",
        quantity: 1,
        isPacked: false,
      },
      {
        tripId: trip.id,
        bagType: "backpack",
        category: "documents",
        itemName: "CNH",
        quantity: 1,
        isPacked: false,
      },
      {
        tripId: trip.id,
        bagType: "backpack",
        category: "documents",
        itemName: "PID",
        quantity: 1,
        isPacked: false,
      },

      // Mala principal
      {
        tripId: trip.id,
        bagType: "checked",
        category: "clothing",
        itemName: "Camisetas",
        quantity: 5,
        isPacked: false,
      },
      {
        tripId: trip.id,
        bagType: "checked",
        category: "clothing",
        itemName: "Camisas ou polos",
        quantity: 2,
        isPacked: false,
      },
      {
        tripId: trip.id,
        bagType: "checked",
        category: "clothing",
        itemName: "Calças",
        quantity: 2,
        isPacked: false,
      },
      {
        tripId: trip.id,
        bagType: "checked",
        category: "clothing",
        itemName: "Bermudas",
        quantity: 2,
        isPacked: false,
      },
      {
        tripId: trip.id,
        bagType: "checked",
        category: "clothing",
        itemName: "Cuecas",
        quantity: 8,
        isPacked: false,
      },
      {
        tripId: trip.id,
        bagType: "checked",
        category: "clothing",
        itemName: "Meias",
        quantity: 8,
        isPacked: false,
      },
      {
        tripId: trip.id,
        bagType: "checked",
        category: "clothing",
        itemName: "Moletom / hoodie",
        quantity: 1,
        isPacked: false,
      },
      {
        tripId: trip.id,
        bagType: "checked",
        category: "clothing",
        itemName: "Jaqueta leve",
        quantity: 1,
        isPacked: false,
      },
      {
        tripId: trip.id,
        bagType: "checked",
        category: "clothing",
        itemName: "Pijama",
        quantity: 1,
        isPacked: false,
      },
      {
        tripId: trip.id,
        bagType: "checked",
        category: "clothing",
        itemName: "Tênis principal confortável",
        quantity: 1,
        isPacked: false,
      },
      {
        tripId: trip.id,
        bagType: "checked",
        category: "accessories",
        itemName: "Chinelo",
        quantity: 1,
        isPacked: false,
      },
      {
        tripId: trip.id,
        bagType: "checked",
        category: "toiletries",
        itemName: "Escova de dentes",
        quantity: 1,
        isPacked: false,
      },
      {
        tripId: trip.id,
        bagType: "checked",
        category: "toiletries",
        itemName: "Pasta de dente",
        quantity: 1,
        isPacked: false,
      },
      {
        tripId: trip.id,
        bagType: "checked",
        category: "toiletries",
        itemName: "Desodorante",
        quantity: 1,
        isPacked: false,
      },
      {
        tripId: trip.id,
        bagType: "checked",
        category: "health",
        itemName: "Medicamentos de uso pessoal",
        quantity: 1,
        isPacked: false,
      },
      {
        tripId: trip.id,
        bagType: "checked",
        category: "accessories",
        itemName: "Adaptador de tomada europeu",
        quantity: 1,
        isPacked: false,
      },
    ],
  });

  // Cidades
  const cityRows = [
    {
      name: "Madrid",
      country: "Spain",
      arrivalDate: "2026-04-07",
      departureDate: "2026-04-11",
      sortOrder: 1,
      notes: "Chegada internacional e primeiros dias de adaptação.",
    },
    {
      name: "Granada",
      country: "Spain",
      arrivalDate: "2026-04-11",
      departureDate: "2026-04-15",
      sortOrder: 2,
      notes: "Avaliar cidade, Alhambra e vida local andaluza.",
    },
    {
      name: "Málaga",
      country: "Spain",
      arrivalDate: "2026-04-15",
      departureDate: "2026-04-20",
      sortOrder: 3,
      notes: "Base para sentir a Costa del Sol e possivelmente encontrar contato pessoal.",
    },
    {
      name: "Valencia",
      country: "Spain",
      arrivalDate: "2026-04-20",
      departureDate: "2026-04-24",
      sortOrder: 4,
      notes: "Cidade forte candidata para avaliar moradia.",
    },
    {
      name: "Benidorm",
      country: "Spain",
      arrivalDate: "2026-04-24",
      departureDate: "2026-04-26",
      sortOrder: 5,
      notes: "Ver cidade vertical/turística e perfil de moradores estrangeiros.",
    },
    {
      name: "Barcelona",
      country: "Spain",
      arrivalDate: "2026-04-26",
      departureDate: "2026-05-01",
      sortOrder: 6,
      notes: "Mesmo sem intenção clara de morar, vale avaliar peso real da cidade.",
    },
    {
      name: "San Sebastián",
      country: "Spain",
      arrivalDate: "2026-05-01",
      departureDate: "2026-05-04",
      sortOrder: 7,
      notes: "Cidade bonita, cara e organizada; ver se o custo se justifica.",
    },
    {
      name: "Santander",
      country: "Spain",
      arrivalDate: "2026-05-04",
      departureDate: "2026-05-06",
      sortOrder: 8,
      notes: "Comparar com San Sebastián e sentir o norte com menos pressão turística.",
    },
    {
      name: "Madrid",
      country: "Spain",
      arrivalDate: "2026-05-06",
      departureDate: "2026-05-07",
      sortOrder: 9,
      notes: "Última noite antes do voo de volta.",
    },
  ];

  const createdCities = [];
  for (const city of cityRows) {
    const created = await prisma.tripCity.create({
      data: {
        tripId: trip.id,
        ...city,
      },
    });
    createdCities.push(created);
  }

  const cityMap = {
    madrid1: createdCities[0],
    granada: createdCities[1],
    malaga: createdCities[2],
    valencia: createdCities[3],
    benidorm: createdCities[4],
    barcelona: createdCities[5],
    sanSebastian: createdCities[6],
    santander: createdCities[7],
    madrid2: createdCities[8],
  };

  // Segmentos
  await prisma.segment.createMany({
    data: [
      {
        tripId: trip.id,
        fromCityId: cityMap.madrid1.id,
        toCityId: cityMap.granada.id,
        transportType: "train",
        departureDatetime: "2026-04-11T09:30:00",
        arrivalDatetime: "2026-04-11T13:05:00",
        provider: "Renfe",
        bookingReference: "TO_BOOK_MAD_GRX",
        notes: "AVE/Larga Distancia; comprar quando fechar datas.",
      },
      {
        tripId: trip.id,
        fromCityId: cityMap.granada.id,
        toCityId: cityMap.malaga.id,
        transportType: "train",
        departureDatetime: "2026-04-15T11:00:00",
        arrivalDatetime: "2026-04-15T12:35:00",
        provider: "Renfe",
        bookingReference: "TO_BOOK_GRX_AGP",
        notes: "Trecho curto e simples.",
      },
      {
        tripId: trip.id,
        fromCityId: cityMap.malaga.id,
        toCityId: cityMap.valencia.id,
        transportType: "train",
        departureDatetime: "2026-04-20T09:15:00",
        arrivalDatetime: "2026-04-20T14:55:00",
        provider: "Renfe",
        bookingReference: "TO_BOOK_AGP_VLC",
        notes: "Alta distância pela costa/centro-leste.",
      },
      {
        tripId: trip.id,
        fromCityId: cityMap.valencia.id,
        toCityId: cityMap.benidorm.id,
        transportType: "train",
        departureDatetime: "2026-04-24T10:00:00",
        arrivalDatetime: "2026-04-24T11:50:00",
        provider: "Renfe + Tram",
        bookingReference: "TO_BOOK_VLC_BEN",
        notes: "Checar integração final local.",
      },
      {
        tripId: trip.id,
        fromCityId: cityMap.benidorm.id,
        toCityId: cityMap.barcelona.id,
        transportType: "train",
        departureDatetime: "2026-04-26T09:30:00",
        arrivalDatetime: "2026-04-26T14:10:00",
        provider: "Renfe",
        bookingReference: "TO_BOOK_BEN_BCN",
        notes: "Pode exigir ajuste fino de conexão dependendo da origem exata.",
      },
      {
        tripId: trip.id,
        fromCityId: cityMap.barcelona.id,
        toCityId: cityMap.sanSebastian.id,
        transportType: "train",
        departureDatetime: "2026-05-01T08:45:00",
        arrivalDatetime: "2026-05-01T14:45:00",
        provider: "Renfe",
        bookingReference: "TO_BOOK_BCN_EAS",
        notes: "Trecho longo; avaliar também voo se preço estiver muito melhor.",
      },
      {
        tripId: trip.id,
        fromCityId: cityMap.sanSebastian.id,
        toCityId: cityMap.santander.id,
        transportType: "bus",
        departureDatetime: "2026-05-04T10:00:00",
        arrivalDatetime: "2026-05-04T13:15:00",
        provider: "ALSA",
        bookingReference: "TO_BOOK_EAS_SDR",
        notes: "Ônibus pode ser mais direto que trem nesse trecho.",
      },
      {
        tripId: trip.id,
        fromCityId: cityMap.santander.id,
        toCityId: cityMap.madrid2.id,
        transportType: "train",
        departureDatetime: "2026-05-06T10:30:00",
        arrivalDatetime: "2026-05-06T14:45:00",
        provider: "Renfe",
        bookingReference: "TO_BOOK_SDR_MAD",
        notes: "Volta para pegar voo internacional no dia seguinte.",
      },
    ],
  });

  // Bookings
  await prisma.booking.createMany({
    data: [
      {
        tripId: trip.id,
        cityId: cityMap.madrid1.id,
        type: "flight",
        title: "Brasil -> Madrid",
        provider: "TO_BOOK",
        bookingCode: "TO_BOOK_INTL_OUTBOUND",
        startDatetime: "2026-04-06T20:00:00",
        endDatetime: "2026-04-07T12:00:00",
        priceAmount: 0,
        priceCurrency: "EUR",
        paymentStatus: "pending",
        address: "",
        notes: "Comprar quando fechar datas e origem exata no Brasil.",
      },
      {
        tripId: trip.id,
        cityId: cityMap.madrid2.id,
        type: "flight",
        title: "Madrid -> Brasil",
        provider: "TO_BOOK",
        bookingCode: "TO_BOOK_INTL_RETURN",
        startDatetime: "2026-05-07T13:00:00",
        endDatetime: "2026-05-08T06:00:00",
        priceAmount: 0,
        priceCurrency: "EUR",
        paymentStatus: "pending",
        address: "",
        notes: "Retorno ao Brasil.",
      },
      {
        tripId: trip.id,
        cityId: cityMap.madrid1.id,
        type: "accommodation",
        title: "Madrid - first stay",
        provider: "Airbnb/Booking",
        bookingCode: "TO_BOOK_MADRID_1",
        startDatetime: "2026-04-07T15:00:00",
        endDatetime: "2026-04-11T11:00:00",
        priceAmount: 420,
        priceCurrency: "EUR",
        paymentStatus: "pending",
        address: "Central Madrid area",
        notes: "Preferência por localização prática para adaptação e deslocamentos.",
      },
      {
        tripId: trip.id,
        cityId: cityMap.granada.id,
        type: "accommodation",
        title: "Granada stay",
        provider: "Booking",
        bookingCode: "TO_BOOK_GRANADA",
        startDatetime: "2026-04-11T15:00:00",
        endDatetime: "2026-04-15T11:00:00",
        priceAmount: 320,
        priceCurrency: "EUR",
        paymentStatus: "pending",
        address: "Centro / Albaicín proximity",
        notes: "Ver custo x localização x conforto.",
      },
      {
        tripId: trip.id,
        cityId: cityMap.malaga.id,
        type: "accommodation",
        title: "Málaga stay",
        provider: "Booking",
        bookingCode: "TO_BOOK_MALAGA",
        startDatetime: "2026-04-15T15:00:00",
        endDatetime: "2026-04-20T11:00:00",
        priceAmount: 475,
        priceCurrency: "EUR",
        paymentStatus: "pending",
        address: "Centro / Soho / La Malagueta",
        notes: "Boa base para explorar e encontrar contato local.",
      },
      {
        tripId: trip.id,
        cityId: cityMap.valencia.id,
        type: "accommodation",
        title: "Valencia stay",
        provider: "Booking",
        bookingCode: "TO_BOOK_VALENCIA",
        startDatetime: "2026-04-20T15:00:00",
        endDatetime: "2026-04-24T11:00:00",
        priceAmount: 380,
        priceCurrency: "EUR",
        paymentStatus: "pending",
        address: "Ruzafa / Eixample / Ciutat Vella",
        notes: "Cidade fortemente candidata; escolher localização que ajude a sentir a vida real.",
      },
      {
        tripId: trip.id,
        cityId: cityMap.benidorm.id,
        type: "accommodation",
        title: "Benidorm stay",
        provider: "Booking",
        bookingCode: "TO_BOOK_BENIDORM",
        startDatetime: "2026-04-24T15:00:00",
        endDatetime: "2026-04-26T11:00:00",
        priceAmount: 180,
        priceCurrency: "EUR",
        paymentStatus: "pending",
        address: "Centro / Levante",
        notes: "Estadia curta, foco em observar perfil da cidade.",
      },
      {
        tripId: trip.id,
        cityId: cityMap.barcelona.id,
        type: "accommodation",
        title: "Barcelona stay",
        provider: "Booking",
        bookingCode: "TO_BOOK_BARCELONA",
        startDatetime: "2026-04-26T15:00:00",
        endDatetime: "2026-05-01T11:00:00",
        priceAmount: 650,
        priceCurrency: "EUR",
        paymentStatus: "pending",
        address: "Eixample / Gràcia",
        notes: "Mais caro; usar para benchmark real.",
      },
      {
        tripId: trip.id,
        cityId: cityMap.sanSebastian.id,
        type: "accommodation",
        title: "San Sebastián stay",
        provider: "Booking",
        bookingCode: "TO_BOOK_SANSEBASTIAN",
        startDatetime: "2026-05-01T15:00:00",
        endDatetime: "2026-05-04T11:00:00",
        priceAmount: 420,
        priceCurrency: "EUR",
        paymentStatus: "pending",
        address: "Centro / La Concha area",
        notes: "Cidade cara; observar se qualidade compensa.",
      },
      {
        tripId: trip.id,
        cityId: cityMap.santander.id,
        type: "accommodation",
        title: "Santander stay",
        provider: "Booking",
        bookingCode: "TO_BOOK_SANTANDER",
        startDatetime: "2026-05-04T15:00:00",
        endDatetime: "2026-05-06T11:00:00",
        priceAmount: 220,
        priceCurrency: "EUR",
        paymentStatus: "pending",
        address: "Centro / Sardinero proximity",
        notes: "Estadia curta para comparar norte da Espanha.",
      },
      {
        tripId: trip.id,
        cityId: cityMap.madrid2.id,
        type: "accommodation",
        title: "Madrid - final night",
        provider: "Airport hotel / Booking",
        bookingCode: "TO_BOOK_MADRID_2",
        startDatetime: "2026-05-06T15:00:00",
        endDatetime: "2026-05-07T10:00:00",
        priceAmount: 110,
        priceCurrency: "EUR",
        paymentStatus: "pending",
        address: "Madrid / airport practical area",
        notes: "Última noite para reduzir risco no voo de volta.",
      },
      {
        tripId: trip.id,
        cityId: cityMap.madrid1.id,
        type: "event",
        title: "Potential Real Madrid match",
        provider: "Real Madrid official ticketing",
        bookingCode: "TO_CHECK_FIXTURE",
        startDatetime: "2026-04-09T20:00:00",
        endDatetime: "2026-04-09T23:00:00",
        priceAmount: 120,
        priceCurrency: "EUR",
        paymentStatus: "pending",
        address: "Santiago Bernabéu, Madrid",
        notes: "Comprar apenas se houver jogo compatível durante a estadia.",
      },
    ],
  });

  // Contatos úteis
  await prisma.contact.createMany({
    data: [
      {
        tripId: trip.id,
        cityId: cityMap.malaga.id,
        name: "Friend near Málaga",
        type: "friend",
        phone: "ADD_PHONE",
        whatsapp: "ADD_WHATSAPP",
        email: "",
        address: "Mijas / Málaga province (confirm exact location)",
        notes: "Contato pessoal da região. Chamar apenas quando a estadia em Málaga estiver definida.",
        isFavorite: true,
      },
      {
        tripId: trip.id,
        cityId: cityMap.madrid1.id,
        name: "Brazilian Embassy / Consular reference in Spain",
        type: "emergency",
        phone: "",
        whatsapp: "",
        email: "",
        address: "Madrid",
        notes: "Salvar contato oficial real depois.",
        isFavorite: true,
      },
      {
        tripId: trip.id,
        cityId: cityMap.madrid1.id,
        name: "Renfe support",
        type: "other",
        phone: "",
        whatsapp: "",
        email: "",
        address: "",
        notes: "Contato operacional para deslocamentos de trem.",
        isFavorite: false,
      },
      {
        tripId: trip.id,
        cityId: cityMap.madrid1.id,
        name: "Airline support",
        type: "transport",
        phone: "",
        whatsapp: "",
        email: "",
        address: "",
        notes: "Preencher quando escolher companhia aérea.",
        isFavorite: false,
      },
    ],
  });

  // Useful links
  await prisma.usefulLink.createMany({
    data: [
      {
        tripId: trip.id,
        cityId: cityMap.madrid1.id,
        title: "Renfe official",
        url: "https://www.renfe.com/es/en",
        category: "transport",
        notes: "Compra e consulta de trechos de trem.",
      },
      {
        tripId: trip.id,
        cityId: cityMap.madrid1.id,
        title: "Real Madrid official tickets",
        url: "https://www.realmadrid.com/en-US/tickets",
        category: "event",
        notes: "Verificar disponibilidade de jogo durante a estadia.",
      },
      {
        tripId: trip.id,
        cityId: cityMap.madrid1.id,
        title: "Madrid tourism / Spain official portal",
        url: "https://www.spain.info/en/destination/madrid/",
        category: "guide",
        notes: "Referência institucional para Madrid.",
      },
      {
        tripId: trip.id,
        cityId: cityMap.granada.id,
        title: "Granada / Andalusia official tourism",
        url: "https://en.andalucia.org/",
        category: "guide",
        notes: "Base oficial regional para Granada e Málaga.",
      },
      {
        tripId: trip.id,
        cityId: cityMap.malaga.id,
        title: "Málaga / Andalusia official tourism",
        url: "https://en.andalucia.org/",
        category: "guide",
        notes: "Base oficial regional.",
      },
      {
        tripId: trip.id,
        cityId: cityMap.valencia.id,
        title: "Valencia city map",
        url: "https://www.google.com/maps/place/Valencia,+Spain",
        category: "map",
        notes: "Abrir rápido no celular.",
      },
      {
        tripId: trip.id,
        cityId: cityMap.benidorm.id,
        title: "Benidorm city map",
        url: "https://www.google.com/maps/place/Benidorm,+Spain",
        category: "map",
        notes: "Mapa operacional.",
      },
      {
        tripId: trip.id,
        cityId: cityMap.barcelona.id,
        title: "Barcelona official tourism",
        url: "https://www.barcelonaturisme.com/wv3/en/",
        category: "guide",
        notes: "Informações oficiais de turismo e mobilidade.",
      },
      {
        tripId: trip.id,
        cityId: cityMap.sanSebastian.id,
        title: "San Sebastián city map",
        url: "https://www.google.com/maps/place/San+Sebastian,+Spain",
        category: "map",
        notes: "Mapa operacional.",
      },
      {
        tripId: trip.id,
        cityId: cityMap.santander.id,
        title: "Santander city map",
        url: "https://www.google.com/maps/place/Santander,+Spain",
        category: "map",
        notes: "Mapa operacional.",
      },
      {
        tripId: trip.id,
        cityId: cityMap.madrid1.id,
        title: "Spain official travel portal",
        url: "https://www.spain.info/en/",
        category: "guide",
        notes: "Portal oficial geral.",
      },
    ],
  });

  // Tasks
  await prisma.task.createMany({
    data: [
      {
        tripId: trip.id,
        cityId: cityMap.madrid1.id,
        title: "Comprar passagem internacional",
        description: "Fechar voo Brasil -> Madrid -> Brasil.",
        priority: "urgent",
        status: "pending",
        category: "booking",
        dueDate: "2026-03-16",
      },
      {
        tripId: trip.id,
        cityId: cityMap.madrid1.id,
        title: "Reservar primeira hospedagem em Madrid",
        description: "Garantir chegada tranquila sem depender de decisão em cima da hora.",
        priority: "high",
        status: "pending",
        category: "booking",
        dueDate: "2026-03-17",
      },
      {
        tripId: trip.id,
        cityId: cityMap.madrid1.id,
        title: "Contratar seguro viagem",
        description: "Salvar apólice no app e offline.",
        priority: "urgent",
        status: "pending",
        category: "health",
        dueDate: "2026-03-20",
      },
      {
        tripId: trip.id,
        cityId: cityMap.madrid1.id,
        title: "Emitir PID",
        description: "Fazer via DETRAN se mantiver plano de alugar carro.",
        priority: "medium",
        status: "pending",
        category: "document",
        dueDate: "2026-03-18",
      },
      {
        tripId: trip.id,
        cityId: cityMap.madrid1.id,
        title: "Converter saldo para EUR",
        description: "Deixar Revolut pronta antes da viagem.",
        priority: "high",
        status: "pending",
        category: "finance",
        dueDate: "2026-03-21",
      },
      {
        tripId: trip.id,
        cityId: cityMap.madrid1.id,
        title: "Separar dinheiro físico",
        description: "Levar aproximadamente €300 em espécie.",
        priority: "medium",
        status: "pending",
        category: "finance",
        dueDate: "2026-03-28",
      },
      {
        tripId: trip.id,
        cityId: cityMap.malaga.id,
        title: "Avisar contato da região de Málaga",
        description: "Confirmar encontro apenas depois que a estadia em Málaga estiver fechada.",
        priority: "low",
        status: "pending",
        category: "other",
        dueDate: "2026-04-16",
      },
      {
        tripId: trip.id,
        cityId: cityMap.madrid1.id,
        title: "Verificar se há jogo do Real Madrid durante a estadia",
        description: "Comprar se fizer sentido e se os preços não estiverem absurdos.",
        priority: "medium",
        status: "pending",
        category: "research",
        dueDate: "2026-03-25",
      },
      {
        tripId: trip.id,
        cityId: cityMap.madrid1.id,
        title: "Fechar estratégia de internet",
        description: "Escolher entre eSIM e chip local.",
        priority: "medium",
        status: "pending",
        category: "other",
        dueDate: "2026-04-01",
      },
      {
        tripId: trip.id,
        cityId: cityMap.madrid1.id,
        title: "Montar mala enxuta",
        description: "Levar roupa para 7-8 dias e usar lavanderia durante a viagem.",
        priority: "high",
        status: "pending",
        category: "packing",
        dueDate: "2026-04-04",
      },
    ],
  });

  // Notas
  await prisma.note.createMany({
    data: [
      {
        tripId: trip.id,
        cityId: cityMap.madrid1.id,
        title: "Objetivo real da viagem",
        content:
          "Não tratar como turismo puro. Observar bairros, supermercados, ritmo urbano, segurança, mobilidade, custo e sensação real de viver no local.",
        tags: "objetivo,estrategia,moradia",
        pinned: true,
      },
      {
        tripId: trip.id,
        cityId: cityMap.valencia.id,
        title: "Valencia é cidade-chave",
        content:
          "Dar atenção especial à cidade. Comparar custo, estética, clima, mobilidade e possibilidade real de moradia versus Málaga e Granada.",
        tags: "valencia,moradia,prioridade",
        pinned: true,
      },
      {
        tripId: trip.id,
        cityId: cityMap.malaga.id,
        title: "Málaga contato local",
        content:
          "Encontrar contato apenas quando estiver hospedado em Málaga. Não forçar logística a partir de Granada.",
        tags: "malaga,contato,logistica",
        pinned: false,
      },
      {
        tripId: trip.id,
        cityId: cityMap.barcelona.id,
        title: "Barcelona como benchmark",
        content:
          "Mesmo sem intenção clara de morar, usar a experiência para calibrar percepção de custo, turismo excessivo, estrutura e qualidade urbana.",
        tags: "barcelona,benchmark,custo",
        pinned: false,
      },
      {
        tripId: trip.id,
        cityId: cityMap.madrid1.id,
        title: "Dia 1 precisa ser leve",
        content:
          "Chegada internacional: check-in, caminhada leve perto da hospedagem, jantar simples e dormir cedo. Nada pesado no primeiro dia.",
        tags: "madrid,chegada,energia",
        pinned: true,
      },
    ],
  });

  // City reviews iniciais
  await prisma.cityReview.createMany({
    data: [
      {
        tripId: trip.id,
        cityId: cityMap.madrid1.id,
        costScore: 5,
        safetyScore: 8,
        beautyScore: 7,
        climateScore: 7,
        transportScore: 10,
        lifestyleScore: 7,
        pros: "Capital, excelente transporte, muita estrutura, tudo acontece.",
        cons: "Mais cara e intensa; menos alinhada com custo-controlado.",
        finalNotes: "Boa referência, mas não é a aposta principal para morar.",
        wouldLiveHere: false,
      },
      {
        tripId: trip.id,
        cityId: cityMap.granada.id,
        costScore: 8,
        safetyScore: 8,
        beautyScore: 9,
        climateScore: 7,
        transportScore: 6,
        lifestyleScore: 8,
        pros: "Linda, histórica, custo melhor, vibe forte.",
        cons: "Menor mercado e menos estrutura que grandes polos.",
        finalNotes: "Forte candidata emocional/racional, precisa sentir no local.",
        wouldLiveHere: true,
      },
      {
        tripId: trip.id,
        cityId: cityMap.malaga.id,
        costScore: 6,
        safetyScore: 8,
        beautyScore: 8,
        climateScore: 9,
        transportScore: 8,
        lifestyleScore: 9,
        pros: "Clima forte, litoral, boa infraestrutura, apelo internacional.",
        cons: "Mais turística e potencialmente mais cara em áreas desejadas.",
        finalNotes: "Candidata forte para comparar com Valencia.",
        wouldLiveHere: true,
      },
      {
        tripId: trip.id,
        cityId: cityMap.valencia.id,
        costScore: 8,
        safetyScore: 8,
        beautyScore: 8,
        climateScore: 8,
        transportScore: 9,
        lifestyleScore: 9,
        pros: "Equilíbrio entre custo, tamanho, praia e vida urbana.",
        cons: "Ainda precisa validar feeling real e bairros.",
        finalNotes: "Talvez a melhor combinação teórica antes da viagem.",
        wouldLiveHere: true,
      },
      {
        tripId: trip.id,
        cityId: cityMap.benidorm.id,
        costScore: 6,
        safetyScore: 8,
        beautyScore: 6,
        climateScore: 9,
        transportScore: 6,
        lifestyleScore: 5,
        pros: "Clima bom, skyline curioso, vida costeira.",
        cons: "Muito turística, pode parecer artificial para moradia.",
        finalNotes: "Mais observação do que aposta real.",
        wouldLiveHere: false,
      },
      {
        tripId: trip.id,
        cityId: cityMap.barcelona.id,
        costScore: 4,
        safetyScore: 6,
        beautyScore: 9,
        climateScore: 8,
        transportScore: 9,
        lifestyleScore: 7,
        pros: "Cidade global, linda, completa.",
        cons: "Cara, pressionada por turismo e custo imobiliário.",
        finalNotes: "Benchmark urbano, não prioridade de moradia.",
        wouldLiveHere: false,
      },
      {
        tripId: trip.id,
        cityId: cityMap.sanSebastian.id,
        costScore: 3,
        safetyScore: 9,
        beautyScore: 10,
        climateScore: 6,
        transportScore: 7,
        lifestyleScore: 8,
        pros: "Muito bonita, organizada, altíssima qualidade percebida.",
        cons: "Cara demais para o que entrega em escala.",
        finalNotes: "Provavelmente não fecha racionalmente, mas vale ver.",
        wouldLiveHere: false,
      },
      {
        tripId: trip.id,
        cityId: cityMap.santander.id,
        costScore: 6,
        safetyScore: 8,
        beautyScore: 8,
        climateScore: 6,
        transportScore: 6,
        lifestyleScore: 7,
        pros: "Norte bonito e potencialmente menos inflacionado que San Sebastián.",
        cons: "Menos centralidade e menos energia urbana.",
        finalNotes: "Boa cidade para comparar com o resto do norte.",
        wouldLiveHere: false,
      },
      {
        tripId: trip.id,
        cityId: cityMap.madrid2.id,
        costScore: 5,
        safetyScore: 8,
        beautyScore: 7,
        climateScore: 7,
        transportScore: 10,
        lifestyleScore: 7,
        pros: "Retorno prático antes do voo.",
        cons: "Mesmo racional da primeira passagem.",
        finalNotes: "Último checkpoint mental da viagem.",
        wouldLiveHere: false,
      },
    ],
  });

  // Expenses planejados / alguns placeholders realistas
  await prisma.expense.createMany({
    data: [
      {
        tripId: trip.id,
        cityId: cityMap.madrid1.id,
        paymentMethod: "Revolut EUR",
        expenseDate: "2026-04-07",
        category: "food",
        description: "Jantar leve na chegada",
        amount: 18,
        currency: "EUR",
        convertedAmountBase: 18,
        notes: "Primeira refeição pós-check-in.",
      },
      {
        tripId: trip.id,
        cityId: cityMap.madrid1.id,
        paymentMethod: "Revolut EUR",
        expenseDate: "2026-04-08",
        category: "transport",
        description: "Transporte local inicial",
        amount: 10,
        currency: "EUR",
        convertedAmountBase: 10,
        notes: "Metrô / deslocamentos locais.",
      },
      {
        tripId: trip.id,
        cityId: cityMap.granada.id,
        paymentMethod: "Revolut EUR",
        expenseDate: "2026-04-12",
        category: "attraction",
        description: "Alhambra",
        amount: 20,
        currency: "EUR",
        convertedAmountBase: 20,
        notes: "Planejado.",
      },
      {
        tripId: trip.id,
        cityId: cityMap.malaga.id,
        paymentMethod: "Cash EUR",
        expenseDate: "2026-04-17",
        category: "communication",
        description: "Chip / eSIM / recarga local",
        amount: 20,
        currency: "EUR",
        convertedAmountBase: 20,
        notes: "Estimativa.",
      },
      {
        tripId: trip.id,
        cityId: cityMap.valencia.id,
        paymentMethod: "Revolut EUR",
        expenseDate: "2026-04-22",
        category: "food",
        description: "Alimentação diária média",
        amount: 30,
        currency: "EUR",
        convertedAmountBase: 30,
        notes: "Placeholder de orçamento.",
      },
      {
        tripId: trip.id,
        cityId: cityMap.barcelona.id,
        paymentMethod: "Revolut EUR",
        expenseDate: "2026-04-28",
        category: "attraction",
        description: "Sagrada Família / atração principal",
        amount: 30,
        currency: "EUR",
        convertedAmountBase: 30,
        notes: "Estimativa.",
      },
      {
        tripId: trip.id,
        cityId: cityMap.sanSebastian.id,
        paymentMethod: "Cash EUR",
        expenseDate: "2026-05-02",
        category: "food",
        description: "Pintxos / refeição local",
        amount: 25,
        currency: "EUR",
        convertedAmountBase: 25,
        notes: "Estimativa.",
      },
      {
        tripId: trip.id,
        cityId: cityMap.madrid2.id,
        paymentMethod: "Revolut EUR",
        expenseDate: "2026-05-06",
        category: "transport",
        description: "Transfer para área do hotel / aeroporto",
        amount: 15,
        currency: "EUR",
        convertedAmountBase: 15,
        notes: "Estimativa.",
      },
    ],
  });

  // Itinerário dia a dia
  const itineraryData = [
    // Madrid 1
    {
      cityId: cityMap.madrid1.id,
      date: "2026-04-07",
      startTime: "15:00",
      endTime: "17:00",
      title: "Check-in e descanso pós-chegada",
      description: "Chegar, organizar bagagem, banho, descanso curto e adaptação.",
      category: "accommodation",
      address: "Madrid accommodation",
      sortOrder: 1,
    },
    {
      cityId: cityMap.madrid1.id,
      date: "2026-04-07",
      startTime: "18:30",
      endTime: "20:00",
      title: "Caminhada leve pelo entorno da hospedagem",
      description: "Sem pressão turística; apenas sentir a região e jantar leve.",
      category: "activity",
      address: "Central Madrid",
      sortOrder: 2,
    },
    {
      cityId: cityMap.madrid1.id,
      date: "2026-04-08",
      startTime: "10:00",
      endTime: "13:00",
      title: "Puerta del Sol, Plaza Mayor e centro histórico",
      description: "Primeiro reconhecimento do centro clássico de Madrid.",
      category: "attraction",
      address: "Puerta del Sol, Madrid",
      sortOrder: 1,
    },
    {
      cityId: cityMap.madrid1.id,
      date: "2026-04-08",
      startTime: "15:30",
      endTime: "18:00",
      title: "Palácio Real e arredores",
      description: "Passeio urbano e leitura da região.",
      category: "attraction",
      address: "Royal Palace of Madrid",
      sortOrder: 2,
    },
    {
      cityId: cityMap.madrid1.id,
      date: "2026-04-09",
      startTime: "10:30",
      endTime: "13:00",
      title: "Parque do Retiro",
      description: "Ver vida local, caminhada e ritmo do bairro.",
      category: "activity",
      address: "El Retiro Park, Madrid",
      sortOrder: 1,
    },
    {
      cityId: cityMap.madrid1.id,
      date: "2026-04-09",
      startTime: "15:00",
      endTime: "17:30",
      title: "Museu do Prado",
      description: "Museu principal de Madrid.",
      category: "attraction",
      address: "Museo del Prado, Madrid",
      sortOrder: 2,
    },
    {
      cityId: cityMap.madrid1.id,
      date: "2026-04-09",
      startTime: "20:00",
      endTime: "23:00",
      title: "Possível jogo do Real Madrid",
      description: "Somente se houver partida compatível e ingresso razoável.",
      category: "activity",
      address: "Santiago Bernabéu, Madrid",
      sortOrder: 3,
    },
    {
      cityId: cityMap.madrid1.id,
      date: "2026-04-10",
      startTime: "10:30",
      endTime: "13:00",
      title: "Chamberí e áreas residenciais",
      description: "Observar cidade como morador, não como turista.",
      category: "activity",
      address: "Chamberí, Madrid",
      sortOrder: 1,
    },
    {
      cityId: cityMap.madrid1.id,
      date: "2026-04-10",
      startTime: "15:00",
      endTime: "18:00",
      title: "Salamanca e eixos de comércio",
      description: "Ver padrão urbano, comércio e custo percebido.",
      category: "shopping",
      address: "Salamanca, Madrid",
      sortOrder: 2,
    },

    // Granada
    {
      cityId: cityMap.granada.id,
      date: "2026-04-11",
      startTime: "09:30",
      endTime: "13:05",
      title: "Trem Madrid -> Granada",
      description: "Deslocamento principal para Andaluzia.",
      category: "transport",
      address: "Madrid to Granada",
      sortOrder: 1,
    },
    {
      cityId: cityMap.granada.id,
      date: "2026-04-11",
      startTime: "15:30",
      endTime: "17:30",
      title: "Check-in e primeira caminhada em Granada",
      description: "Sentir a cidade sem agenda pesada.",
      category: "accommodation",
      address: "Granada accommodation",
      sortOrder: 2,
    },
    {
      cityId: cityMap.granada.id,
      date: "2026-04-12",
      startTime: "09:30",
      endTime: "13:30",
      title: "Alhambra",
      description: "Principal ponto histórico da cidade.",
      category: "attraction",
      address: "Alhambra, Granada",
      sortOrder: 1,
    },
    {
      cityId: cityMap.granada.id,
      date: "2026-04-12",
      startTime: "17:00",
      endTime: "19:00",
      title: "Mirador de San Nicolás",
      description: "Ver a Alhambra e sentir o Albaicín.",
      category: "activity",
      address: "Mirador de San Nicolás, Granada",
      sortOrder: 2,
    },
    {
      cityId: cityMap.granada.id,
      date: "2026-04-13",
      startTime: "10:30",
      endTime: "13:30",
      title: "Albaicín e centro histórico",
      description: "Exploração de ruas, comércio e vida real da cidade.",
      category: "activity",
      address: "Albaicín, Granada",
      sortOrder: 1,
    },
    {
      cityId: cityMap.granada.id,
      date: "2026-04-14",
      startTime: "11:00",
      endTime: "14:00",
      title: "Dia de observação prática",
      description: "Mercado, supermercados, lavanderia e bairros possíveis.",
      category: "activity",
      address: "Granada",
      sortOrder: 1,
    },

    // Málaga
    {
      cityId: cityMap.malaga.id,
      date: "2026-04-15",
      startTime: "11:00",
      endTime: "12:35",
      title: "Trem Granada -> Málaga",
      description: "Deslocamento para a Costa del Sol.",
      category: "transport",
      address: "Granada to Málaga",
      sortOrder: 1,
    },
    {
      cityId: cityMap.malaga.id,
      date: "2026-04-15",
      startTime: "15:30",
      endTime: "17:30",
      title: "Check-in e caminhada inicial",
      description: "Centro / porto / arredores dependendo da hospedagem.",
      category: "accommodation",
      address: "Málaga accommodation",
      sortOrder: 2,
    },
    {
      cityId: cityMap.malaga.id,
      date: "2026-04-16",
      startTime: "10:30",
      endTime: "13:30",
      title: "Centro histórico e porto",
      description: "Entender a cidade além da imagem turística.",
      category: "activity",
      address: "Centro Histórico, Málaga",
      sortOrder: 1,
    },
    {
      cityId: cityMap.malaga.id,
      date: "2026-04-16",
      startTime: "19:30",
      endTime: "22:00",
      title: "Possível encontro com contato local",
      description: "Só confirmar se a agenda fizer sentido.",
      category: "restaurant",
      address: "Málaga province",
      sortOrder: 2,
    },
    {
      cityId: cityMap.malaga.id,
      date: "2026-04-17",
      startTime: "10:00",
      endTime: "13:00",
      title: "La Malagueta e bairros próximos",
      description: "Analisar qualidade de vida perto do mar.",
      category: "activity",
      address: "La Malagueta, Málaga",
      sortOrder: 1,
    },
    {
      cityId: cityMap.malaga.id,
      date: "2026-04-18",
      startTime: "09:30",
      endTime: "18:00",
      title: "Dia opcional de carro pela Costa del Sol",
      description: "Explorar trajeto para Marbella, Nerja ou arredores se a locação valer a pena.",
      category: "activity",
      address: "Costa del Sol",
      sortOrder: 1,
    },
    {
      cityId: cityMap.malaga.id,
      date: "2026-04-19",
      startTime: "11:00",
      endTime: "14:00",
      title: "Dia de rotina real",
      description: "Supermercado, café, lavanderia, caminhada e observação de custo.",
      category: "activity",
      address: "Málaga",
      sortOrder: 1,
    },

    // Valencia
    {
      cityId: cityMap.valencia.id,
      date: "2026-04-20",
      startTime: "09:15",
      endTime: "14:55",
      title: "Trem Málaga -> Valencia",
      description: "Deslocamento para cidade-chave da viagem.",
      category: "transport",
      address: "Málaga to Valencia",
      sortOrder: 1,
    },
    {
      cityId: cityMap.valencia.id,
      date: "2026-04-20",
      startTime: "16:00",
      endTime: "18:00",
      title: "Check-in e volta curta em Ruzafa/Eixample",
      description: "Primeira leitura da energia urbana.",
      category: "accommodation",
      address: "Valencia accommodation",
      sortOrder: 2,
    },
    {
      cityId: cityMap.valencia.id,
      date: "2026-04-21",
      startTime: "10:00",
      endTime: "13:00",
      title: "Ciutat Vella",
      description: "Centro histórico e ritmo de dia útil.",
      category: "attraction",
      address: "Ciutat Vella, Valencia",
      sortOrder: 1,
    },
    {
      cityId: cityMap.valencia.id,
      date: "2026-04-21",
      startTime: "16:00",
      endTime: "18:30",
      title: "Turia e áreas urbanas ao redor",
      description: "Ver mobilidade, lazer e integração da cidade.",
      category: "activity",
      address: "Turia Gardens, Valencia",
      sortOrder: 2,
    },
    {
      cityId: cityMap.valencia.id,
      date: "2026-04-22",
      startTime: "10:30",
      endTime: "13:30",
      title: "Cidade das Artes e das Ciências",
      description: "Cartão-postal e leitura urbana do entorno.",
      category: "attraction",
      address: "City of Arts and Sciences, Valencia",
      sortOrder: 1,
    },
    {
      cityId: cityMap.valencia.id,
      date: "2026-04-23",
      startTime: "11:00",
      endTime: "15:00",
      title: "Dia de vida real em Valencia",
      description: "Supermercado, bairros residenciais, cafés, transporte e sensação de moradia.",
      category: "activity",
      address: "Valencia",
      sortOrder: 1,
    },

    // Benidorm
    {
      cityId: cityMap.benidorm.id,
      date: "2026-04-24",
      startTime: "10:00",
      endTime: "11:50",
      title: "Valencia -> Benidorm",
      description: "Trecho curto para observação da cidade.",
      category: "transport",
      address: "Valencia to Benidorm",
      sortOrder: 1,
    },
    {
      cityId: cityMap.benidorm.id,
      date: "2026-04-24",
      startTime: "15:30",
      endTime: "18:00",
      title: "Skyline e praia de Levante",
      description: "Primeira leitura do perfil da cidade.",
      category: "activity",
      address: "Levante Beach, Benidorm",
      sortOrder: 2,
    },
    {
      cityId: cityMap.benidorm.id,
      date: "2026-04-25",
      startTime: "11:00",
      endTime: "14:00",
      title: "Old Town e observação de moradores / turismo",
      description: "Entender se a cidade faz qualquer sentido fora do turismo.",
      category: "activity",
      address: "Benidorm Old Town",
      sortOrder: 1,
    },

    // Barcelona
    {
      cityId: cityMap.barcelona.id,
      date: "2026-04-26",
      startTime: "09:30",
      endTime: "14:10",
      title: "Benidorm -> Barcelona",
      description: "Deslocamento para benchmark urbano da viagem.",
      category: "transport",
      address: "Benidorm to Barcelona",
      sortOrder: 1,
    },
    {
      cityId: cityMap.barcelona.id,
      date: "2026-04-26",
      startTime: "16:00",
      endTime: "18:30",
      title: "Check-in e caminhada inicial em Eixample/Gràcia",
      description: "Ler o ambiente e o custo percebido da cidade.",
      category: "accommodation",
      address: "Barcelona accommodation",
      sortOrder: 2,
    },
    {
      cityId: cityMap.barcelona.id,
      date: "2026-04-27",
      startTime: "10:00",
      endTime: "13:00",
      title: "Sagrada Família",
      description: "Ponto principal da cidade.",
      category: "attraction",
      address: "Sagrada Família, Barcelona",
      sortOrder: 1,
    },
    {
      cityId: cityMap.barcelona.id,
      date: "2026-04-27",
      startTime: "16:00",
      endTime: "18:30",
      title: "Passeio por Eixample",
      description: "Ver padrão urbano e vida local.",
      category: "activity",
      address: "Eixample, Barcelona",
      sortOrder: 2,
    },
    {
      cityId: cityMap.barcelona.id,
      date: "2026-04-28",
      startTime: "10:30",
      endTime: "13:30",
      title: "Park Güell",
      description: "Leitura turística e espacial da cidade.",
      category: "attraction",
      address: "Park Güell, Barcelona",
      sortOrder: 1,
    },
    {
      cityId: cityMap.barcelona.id,
      date: "2026-04-29",
      startTime: "11:00",
      endTime: "14:00",
      title: "Barceloneta",
      description: "Entender o eixo praia + turismo na prática.",
      category: "activity",
      address: "Barceloneta, Barcelona",
      sortOrder: 1,
    },
    {
      cityId: cityMap.barcelona.id,
      date: "2026-04-30",
      startTime: "11:00",
      endTime: "15:00",
      title: "Dia de rotina e comparação urbana",
      description: "Supermercado, café, mobilidade, bairros e custo real.",
      category: "activity",
      address: "Barcelona",
      sortOrder: 1,
    },

    // San Sebastián
    {
      cityId: cityMap.sanSebastian.id,
      date: "2026-05-01",
      startTime: "08:45",
      endTime: "14:45",
      title: "Barcelona -> San Sebastián",
      description: "Trecho longo até o norte.",
      category: "transport",
      address: "Barcelona to San Sebastián",
      sortOrder: 1,
    },
    {
      cityId: cityMap.sanSebastian.id,
      date: "2026-05-01",
      startTime: "16:00",
      endTime: "18:30",
      title: "Check-in e primeira volta em La Concha",
      description: "Sentir o padrão da cidade.",
      category: "accommodation",
      address: "San Sebastián accommodation",
      sortOrder: 2,
    },
    {
      cityId: cityMap.sanSebastian.id,
      date: "2026-05-02",
      startTime: "11:00",
      endTime: "14:00",
      title: "La Concha e centro",
      description: "Cidade bonita, observar se o custo é justificável.",
      category: "activity",
      address: "La Concha, San Sebastián",
      sortOrder: 1,
    },
    {
      cityId: cityMap.sanSebastian.id,
      date: "2026-05-02",
      startTime: "19:00",
      endTime: "21:00",
      title: "Pintxos",
      description: "Experiência local clássica.",
      category: "restaurant",
      address: "Old Town, San Sebastián",
      sortOrder: 2,
    },
    {
      cityId: cityMap.sanSebastian.id,
      date: "2026-05-03",
      startTime: "11:00",
      endTime: "15:00",
      title: "Dia de observação prática",
      description: "Ver comércio, mercado, bairros e sensação de moradia real.",
      category: "activity",
      address: "San Sebastián",
      sortOrder: 1,
    },

    // Santander
    {
      cityId: cityMap.santander.id,
      date: "2026-05-04",
      startTime: "10:00",
      endTime: "13:15",
      title: "San Sebastián -> Santander",
      description: "Subida/descida costeira para comparar norte da Espanha.",
      category: "transport",
      address: "San Sebastián to Santander",
      sortOrder: 1,
    },
    {
      cityId: cityMap.santander.id,
      date: "2026-05-04",
      startTime: "16:00",
      endTime: "18:30",
      title: "Check-in e primeira volta",
      description: "Chegada leve para ler a cidade.",
      category: "accommodation",
      address: "Santander accommodation",
      sortOrder: 2,
    },
    {
      cityId: cityMap.santander.id,
      date: "2026-05-05",
      startTime: "10:30",
      endTime: "14:00",
      title: "Centro e El Sardinero",
      description: "Comparação com San Sebastián em custo e sensação geral.",
      category: "activity",
      address: "Santander / El Sardinero",
      sortOrder: 1,
    },

    // Madrid final
    {
      cityId: cityMap.madrid2.id,
      date: "2026-05-06",
      startTime: "10:30",
      endTime: "14:45",
      title: "Santander -> Madrid",
      description: "Retorno final à capital.",
      category: "transport",
      address: "Santander to Madrid",
      sortOrder: 1,
    },
    {
      cityId: cityMap.madrid2.id,
      date: "2026-05-06",
      startTime: "16:00",
      endTime: "18:00",
      title: "Check-in final e organização para volta",
      description: "Separar documentos, revisar bagagem e preparar voo.",
      category: "accommodation",
      address: "Madrid final accommodation",
      sortOrder: 2,
    },
    {
      cityId: cityMap.madrid2.id,
      date: "2026-05-07",
      startTime: "08:00",
      endTime: "10:00",
      title: "Check-out e deslocamento ao aeroporto",
      description: "Encerramento da viagem.",
      category: "transport",
      address: "Madrid airport",
      sortOrder: 1,
    },
  ];

  for (const item of itineraryData) {
    await prisma.itineraryItem.create({
      data: {
        tripId: trip.id,
        ...item,
      },
    });
  }

  console.log(`Seed concluído: ${trip.title}`);
  console.log(`Trip ID: ${trip.id}`);
  console.log(`Cities created: ${createdCities.length}`);
}

main()
  .catch((error) => {
    console.error("Seed failed:", error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });